#!/usr/bin/env python3
import asyncio
from tcp import Servidor
import re


def validar_nome(nome):
    return re.match(br'^[a-zA-Z][a-zA-Z0-9_-]*$', nome) is not None


def sair(conexao):
    print(conexao, 'conexão fechada')
    conexao.fechar()

def dados_recebidos(conexao, dados: bytes):
    print(conexao, dados)
    if dados == b'':
        return sair(conexao)

    if dados.find(b'\n') == -1: #se nao tem \n
        conexao.residual += dados
        return
    elif dados.find(b'\n') != len(dados)-1: #se tem mais coisa depois do primeiro \n
        spl = dados.split(b'\n')
        for i in spl[:-1]:
            dados_recebidos(conexao, i+b'\n')
        if spl[-1]:
            dados_recebidos(conexao, spl[-1])
        return
    if conexao.residual: 
        dados = conexao.residual+dados
    
    if dados.startswith(b'PING'):
        payload = dados.split (b' ')[1]
        conexao.enviar(b':server PONG server :' + payload)
    


def conexao_aceita(conexao):
    print(conexao, 'nova conexão')
    conexao.residual = b''
    conexao.registrar_recebedor(dados_recebidos)


servidor = Servidor(6667)
servidor.registrar_monitor_de_conexoes_aceitas(conexao_aceita)
asyncio.get_event_loop().run_forever()
